"use strict";

/* ===========================================
            DOWNLOAD PDF
=========================================== */

async function downloadPDF() {

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    let y = 20;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("Student Report Card", 65, y);

    y += 15;

    doc.setFontSize(13);
    doc.setFont("helvetica", "normal");

    doc.text(`Student Name : ${nameInput.value}`, 20, y);

    y += 10;

    doc.text(`Roll Number : ${rollInput.value}`, 20, y);

    y += 10;

    doc.text(`Total Marks : ${total}`, 20, y);

    y += 10;

    doc.text(`Percentage : ${percent.toFixed(2)}%`, 20, y);

    y += 10;

    doc.text(`Grade : ${finalGrade}`, 20, y);

    y += 10;

    doc.text(`Status : ${finalStatus}`, 20, y);

    y += 20;

    doc.setFont("helvetica", "bold");

    doc.text("Subject", 20, y);
    doc.text("Marks", 120, y);
    doc.text("Status", 165, y);

    y += 8;

    doc.line(20, y, 190, y);

    y += 10;

    doc.setFont("helvetica", "normal");

    reportData.forEach(item => {

        if (y > 270) {

            doc.addPage();

            y = 20;

        }

        doc.text(item.subject, 20, y);

        doc.text(String(item.marks), 125, y);

        doc.text(item.status, 165, y);

        y += 10;

    });

    y += 15;

    doc.setFont("helvetica", "italic");

    doc.text(
        "Generated by Student Marks Manager",
        50,
        y
    );

    doc.save(`${nameInput.value}_Report.pdf`);

}